# Generated by Django 4.0.3 on 2022-04-09 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uploadDate',
        ),
        migrations.AddField(
            model_name='item',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
