# Generated by Django 4.0.3 on 2022-04-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_item_image_itemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data',
            new_name='imageData',
        ),
    ]
