# Generated by Django 4.0.4 on 2022-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_data_image_imagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='emplacement',
            field=models.CharField(default='tunis', max_length=100),
        ),
    ]
