# Generated by Django 4.0.4 on 2022-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_item_emplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageData',
            field=models.TextField(),
        ),
    ]
