# Generated by Django 4.0.4 on 2022-06-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_image_imagedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administrator',
        ),
    ]
